package org.valz.util.protocol;

public enum MessageType {
    GET_VALUE_REQUEST,
    GET_VALUE_RESPONSE,
    GET_AGGREGATE_REQUEST,
    GET_AGGREGATE_RESPONSE,
    LIST_VARS_REQUEST,
    LIST_VARS_RESPONSE,
    SUBMIT_REQUEST,
}
